import type { Pirate } from "./crew-types"

export const INITIAL_CREW: Pirate[] = [
  {
    id: "p-anne",
    name: "Anne Bonny",
    epithet: "The Tempest",
    role: "Captain",
    origin: "Kinsale",
    yearsAtSea: 14,
    skills: { swordsmanship: 92, gunnery: 74, navigation: 88, rigging: 60, stealth: 71, medicine: 40 },
    vitals: { health: 88, scurvy: 12, morale: 90 },
  },
  {
    id: "p-mary",
    name: "Mary Read",
    epithet: "The Ghost",
    role: "Quartermaster",
    origin: "London",
    yearsAtSea: 12,
    skills: { swordsmanship: 89, gunnery: 66, navigation: 80, rigging: 58, stealth: 84, medicine: 55 },
    vitals: { health: 82, scurvy: 20, morale: 78 },
  },
  {
    id: "p-caesar",
    name: "Black Caesar",
    epithet: "Iron Fist",
    role: "Bosun",
    origin: "West Africa",
    yearsAtSea: 16,
    skills: { swordsmanship: 85, gunnery: 70, navigation: 62, rigging: 90, stealth: 55, medicine: 44 },
    vitals: { health: 91, scurvy: 8, morale: 84 },
  },
  {
    id: "p-cannon",
    name: "Bartholomew Vane",
    epithet: "Powderkeg",
    role: "Master Gunner",
    origin: "Bristol",
    yearsAtSea: 11,
    skills: { swordsmanship: 60, gunnery: 96, navigation: 52, rigging: 64, stealth: 42, medicine: 30 },
    vitals: { health: 70, scurvy: 34, morale: 66 },
  },
  {
    id: "p-hawk",
    name: "Ling Hawke",
    epithet: "Falcon Eye",
    role: "Lookout",
    origin: "Macau",
    yearsAtSea: 7,
    skills: { swordsmanship: 55, gunnery: 48, navigation: 90, rigging: 72, stealth: 88, medicine: 38 },
    vitals: { health: 86, scurvy: 15, morale: 80 },
  },
  {
    id: "p-timber",
    name: "Olaf Timmerman",
    epithet: "Old Timber",
    role: "Shipwright",
    origin: "Rotterdam",
    yearsAtSea: 22,
    skills: { swordsmanship: 45, gunnery: 50, navigation: 58, rigging: 95, stealth: 40, medicine: 60 },
    vitals: { health: 64, scurvy: 42, morale: 58 },
  },
  {
    id: "p-doc",
    name: "Esperanza Cruz",
    epithet: "The Mender",
    role: "Deckhand",
    origin: "Cartagena",
    yearsAtSea: 6,
    skills: { swordsmanship: 50, gunnery: 40, navigation: 64, rigging: 66, stealth: 60, medicine: 94 },
    vitals: { health: 90, scurvy: 6, morale: 88 },
  },
  {
    id: "p-shadow",
    name: "Kaito Shimizu",
    epithet: "Nightfall",
    role: "Deckhand",
    origin: "Nagasaki",
    yearsAtSea: 5,
    skills: { swordsmanship: 78, gunnery: 44, navigation: 55, rigging: 62, stealth: 95, medicine: 36 },
    vitals: { health: 84, scurvy: 18, morale: 72 },
  },
  {
    id: "p-scar",
    name: "Diego Salazar",
    epithet: "Scarhand",
    role: "Deckhand",
    origin: "Havana",
    yearsAtSea: 9,
    skills: { swordsmanship: 82, gunnery: 72, navigation: 48, rigging: 70, stealth: 50, medicine: 28 },
    vitals: { health: 58, scurvy: 55, morale: 47 },
  },
  {
    id: "p-gale",
    name: "Freya Storm",
    epithet: "Sea Gale",
    role: "Lookout",
    origin: "Bergen",
    yearsAtSea: 8,
    skills: { swordsmanship: 63, gunnery: 55, navigation: 86, rigging: 80, stealth: 74, medicine: 42 },
    vitals: { health: 79, scurvy: 22, morale: 76 },
  },
  {
    id: "p-brass",
    name: "Cormac O'Dell",
    epithet: "Brass Knuckle",
    role: "Master Gunner",
    origin: "Galway",
    yearsAtSea: 13,
    skills: { swordsmanship: 68, gunnery: 90, navigation: 50, rigging: 58, stealth: 46, medicine: 33 },
    vitals: { health: 74, scurvy: 28, morale: 62 },
  },
  {
    id: "p-reef",
    name: "Tamsin Vale",
    epithet: "Reefrunner",
    role: "Deckhand",
    origin: "Port Royal",
    yearsAtSea: 4,
    skills: { swordsmanship: 58, gunnery: 46, navigation: 70, rigging: 84, stealth: 66, medicine: 52 },
    vitals: { health: 92, scurvy: 5, morale: 85 },
  },
]
